services:
  web:
    build: .
    ports:
      - "4992:4992"
    command: python ./app/app.py
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - ./app:/app/app
    
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
    driver: local