services:
  db:
    image: postgres:15-alpine
    container_name: myapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - myapp_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: myapp-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  myapp_db_data:
