version: "3.9"

services:
  db:
    image: postgres:15
    container_name: chat_genius_db
    environment:
      - POSTGRES_DB=chatgenius
      - POSTGRES_USER=chatgenius
      - POSTGRES_PASSWORD=chatgeniuspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: chat_genius_web
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://chatgenius:chatgeniuspass@db:5432/chatgenius
    command: ["python", "-m", "app.main"]

volumes:
  pgdata:

