# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: chat_genius_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 25

  web:
    build: .
    container_name: chat_genius_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - AUTH_REQUIRED=True
    volumes:
      - .:/app
    command: gunicorn --worker-class eventlet --reload --bind 0.0.0.0:5000 app.main:app

volumes:
  pgdata:

